#!/usr/bin/env python3
"""
YouTube AI Autopilot - Main Script
एक पूरी तरह automated YouTube channel जो:
- AI से trading topics generate करता है
- Scripts खुद लिखता है
- Videos बनाता है
- YouTube पर upload करता है
"""

import json
import os
import sys
import schedule
import time
import logging
from datetime import datetime
from modules.topic_generator import TopicGenerator
from modules.script_writer import ScriptWriter
from modules.video_generator import VideoGenerator
from modules.youtube_uploader import YouTubeUploader
from modules.scheduler import TaskScheduler

# Logging setup
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler('logs/autopilot.log'),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger(__name__)

class YouTubeAutopilot:
    def __init__(self, config_path='config.json'):
        """Initialize the autopilot system"""
        self.config = self.load_config(config_path)
        self.topic_generator = TopicGenerator(self.config)
        self.script_writer = ScriptWriter(self.config)
        self.video_generator = VideoGenerator(self.config)
        self.youtube_uploader = YouTubeUploader(self.config)
        logger.info("✅ YouTube AI Autopilot initialized")
    
    def load_config(self, config_path):
        """Load configuration from JSON file"""
        try:
            with open(config_path, 'r', encoding='utf-8') as f:
                config = json.load(f)
            logger.info(f"✅ Configuration loaded from {config_path}")
            return config
        except FileNotFoundError:
            logger.error(f"❌ Config file not found: {config_path}")
            logger.info("💡 Copy config.example.json to config.json और अपनी API keys डालें")
            sys.exit(1)
    
    def generate_video_content(self, custom_topic=None):
        """
        पूरी process: Topic → Script → Video → Upload
        """
        try:
            logger.info("🚀 Starting video content generation...")
            
            # Step 1: Generate Topic
            logger.info("📚 Step 1: Generating topic...")
            if custom_topic:
                topic = custom_topic
                logger.info(f"Using custom topic: {topic}")
            else:
                topic = self.topic_generator.generate_topic()
            logger.info(f"✅ Topic generated: {topic}")
            
            # Step 2: Write Script
            logger.info("✍️  Step 2: Writing script...")
            script_hindi = self.script_writer.write_script(topic, language='hindi')
            script_english = self.script_writer.write_script(topic, language='english')
            logger.info("✅ Scripts written (Hindi + English)")
            
            # Step 3: Generate Video
            logger.info("🎬 Step 3: Generating video...")
            video_path = self.video_generator.generate_video(
                topic=topic,
                script_hindi=script_hindi,
                script_english=script_english
            )
            logger.info(f"✅ Video generated: {video_path}")
            
            # Step 4: Upload to YouTube
            logger.info("📤 Step 4: Uploading to YouTube...")
            video_url = self.youtube_uploader.upload_video(
                video_path=video_path,
                title=topic,
                description=self.generate_description(topic, script_hindi),
                tags=['trading', 'finance', 'investing', 'ai', 'automation']
            )
            logger.info(f"✅ Video uploaded successfully!")
            logger.info(f"🎥 Watch here: {video_url}")
            
            # Save to history
            self.save_to_history(topic, video_path, video_url)
            
            return {
                'status': 'success',
                'topic': topic,
                'video_url': video_url,
                'timestamp': datetime.now().isoformat()
            }
            
        except Exception as e:
            logger.error(f"❌ Error during content generation: {str(e)}")
            return {'status': 'error', 'error': str(e)}
    
    def generate_description(self, topic, script):
        """Generate video description"""
        description = f"""
{topic}

📚 इस वीडियो में हमने {topic} के बारे में विस्तार से बताया है।

⏰ Timestamps:
0:00 - Introduction
5:00 - Main Content
10:00 - Conclusion

🔔 Subscribe करें नई वीडियोज के लिए!

#Trading #Finance #Investing #AI

---
Generated by YouTube AI Autopilot
Learn More: https://github.com/surajlakahra-commits/youtube-ai-autopilot
        """
        return description.strip()
    
    def save_to_history(self, topic, video_path, video_url):
        """Save generated content to history"""
        history_file = 'data/uploaded_videos.json'
        
        # Create data directory if not exists
        os.makedirs('data', exist_ok=True)
        
        # Load existing history
        if os.path.exists(history_file):
            with open(history_file, 'r', encoding='utf-8') as f:
                history = json.load(f)
        else:
            history = []
        
        # Add new entry
        history.append({
            'topic': topic,
            'video_path': video_path,
            'video_url': video_url,
            'timestamp': datetime.now().isoformat()
        })
        
        # Save updated history
        with open(history_file, 'w', encoding='utf-8') as f:
            json.dump(history, f, indent=2, ensure_ascii=False)
        
        logger.info(f"✅ History saved to {history_file}")
    
    def schedule_uploads(self):
        """Setup scheduled uploads"""
        logger.info("⏰ Setting up scheduled uploads...")
        
        upload_time = self.config.get('automation', {}).get('upload_time', '10:00')
        
        schedule.every().day.at(upload_time).do(self.generate_video_content)
        logger.info(f"✅ Scheduled to upload daily at {upload_time}")
        
        # Keep scheduler running
        logger.info("🔄 Autopilot is running... Press Ctrl+C to stop")
        while True:
            try:
                schedule.run_pending()
                time.sleep(60)
            except KeyboardInterrupt:
                logger.info("⏹️  Autopilot stopped by user")
                break
            except Exception as e:
                logger.error(f"❌ Scheduler error: {str(e)}")
                time.sleep(60)

def main():
    """Main entry point"""
    import argparse
    
    parser = argparse.ArgumentParser(description='YouTube AI Autopilot')
    parser.add_argument('--once', action='store_true', help='Run once and exit')
    parser.add_argument('--schedule', action='store_true', help='Run in scheduled mode')
    parser.add_argument('--topic', type=str, help='Custom topic to generate')
    parser.add_argument('--config', type=str, default='config.json', help='Config file path')
    
    args = parser.parse_args()
    
    # Create necessary directories
    os.makedirs('logs', exist_ok=True)
    os.makedirs('data', exist_ok=True)
    os.makedirs('output', exist_ok=True)
    
    # Initialize autopilot
    autopilot = YouTubeAutopilot(args.config)
    
    if args.once:
        # Run once
        logger.info("🎬 Running one-time content generation...")
        result = autopilot.generate_video_content(custom_topic=args.topic)
        print("\n" + "="*50)
        print(json.dumps(result, indent=2, ensure_ascii=False))
        print("="*50)
    
    elif args.schedule:
        # Run in schedule mode
        logger.info("📅 Starting scheduled autopilot mode...")
        autopilot.schedule_uploads()
    
    else:
        # Show help
        parser.print_help()

if __name__ == '__main__':
    main()
